// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterData, CounterTableId } from "./tables/Counter.sol";
import { BalanceTable, BalanceTableTableId } from "./tables/BalanceTable.sol";
